apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nextjs-nginx-app
  name: nextjs-nginx-app
spec:
  selector:
    matchLabels:
      app: nextjsapp
  template:
    metadata:
      labels:
        app: nextjsapp
    spec:
      containers:
        - name: app
          image: docker.io/amikhailov2gis/nextjs-k8s
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
